# Generated by Django 5.0.3 on 2024-03-12 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='birth_date',
        ),
    ]
