# Generated by Django 5.0.3 on 2024-03-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_remove_profil_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
